project:
  type: website
  output-dir: docs

website:
  title: "Robbin Romijnders"
  navbar:
    left:
      - text: "About"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Talks"
        href: talks.qmd
      # - text: "Blog"
      #   href: posts.qmd
    right: 
      - icon: github
        href: https://github.com/rmndrs89
      - icon: linkedin
        href: https://www.linkedin.com/in/robbinromijnders/
  page-footer: "Â© Robbin Romijnders"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



