project:
  type: website
  output-dir: docs

website:
  title: "Robbin Romijnders"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Blog"
        href: posts.qmd
      - about.qmd
    right: 
      - icon: github
        href: https://github.com/rmndrs89
      - icon: linkedin
        href: https://www.linkedin.com/in/robbinromijnders/
  page-footer: "Â© Robbin Romijnders"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



